/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmployeesPanel.java
 *
 * Created on 18.mar.2011, 10:16:19
 */

package no.ntnu.fp.gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import no.ntnu.fp.model.Communication;
import no.ntnu.fp.model.IPersonListener;
import no.ntnu.fp.model.Person;

/**
 *
 * @author Erlend Dahl
 */
public class EmployeesPanel extends javax.swing.JPanel {

    DefaultListModel dlm = new DefaultListModel();
    List<IPersonListener> personListeners = new ArrayList<IPersonListener>();

    /** Creates new form EmployeesPanel */
    public EmployeesPanel() {
        initComponents();

        lstEmployees.setModel(dlm);
        for(Person p : Communication.getEmployees())
            dlm.addElement(p);
    }

    public void addListener(IPersonListener ipl)
    {
        personListeners.add(ipl);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstEmployees = new javax.swing.JList();
        btnShowCalendar = new javax.swing.JButton();

        lstEmployees.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstEmployees.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstEmployees.setCellRenderer(new AllEmployeesListRenderer());
        lstEmployees.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEmployeesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstEmployees);

        btnShowCalendar.setText("Vis kalender");
        btnShowCalendar.setEnabled(false);
        btnShowCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCalendarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnShowCalendar)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowCalendar))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lstEmployeesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEmployeesValueChanged
        btnShowCalendar.setEnabled(lstEmployees.getSelectedIndex()>-1);
    }//GEN-LAST:event_lstEmployeesValueChanged

    private void btnShowCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCalendarActionPerformed
        for(IPersonListener ipl : personListeners)
            ipl.personAction((Person)dlm.getElementAt(lstEmployees.getSelectedIndex()));
    }//GEN-LAST:event_btnShowCalendarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowCalendar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstEmployees;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[])
    {
        EmployeesPanel p = new EmployeesPanel();
        JFrame frame = new JFrame();
        frame.getContentPane().add(p);
        frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        
    }

}
