/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MessagePanel.java
 *
 * Created on 17.mar.2011, 09:30:23
 */

package no.ntnu.fp.gui;

import com.sun.xml.internal.messaging.saaj.soap.ver1_1.Message1_1Impl;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

import no.ntnu.fp.model.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author Erlend Dahl
 */
public class MessagePanel extends javax.swing.JPanel {

    /** Creates new form MessagePanel */
    public MessagePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblContents = new javax.swing.JLabel();
        lblInvitation = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText("Message sent:");

        lblDate.setText("17-12-2001");
        lblDate.setName("lblDate"); // NOI18N

        lblContents.setText("jLabel3");
        lblContents.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblContents.setName("lblText"); // NOI18N
        lblContents.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblInvitation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInvitation.setText("Invitation");
        lblInvitation.setName("lblMessageType"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(366, Short.MAX_VALUE)
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblDate)
        			.addContainerGap())
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblInvitation)
        			.addContainerGap(423, Short.MAX_VALUE))
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblContents, GroupLayout.PREFERRED_SIZE, 370, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(8)
        			.addComponent(lblInvitation)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblContents, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblDate)
        				.addComponent(jLabel1))
        			.addContainerGap())
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblContents;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblInvitation;
    // End of variables declaration//GEN-END:variables

    Message message;
    public void readMessage(Message m)
    {
        message=m;

        //Set Look & Feel
        try {
                javax.swing.UIManager.setLookAndFeel("com.jgoodies.looks.plastic.PlasticXPLookAndFeel");
        } catch(Exception e) {
                e.printStackTrace();
        }
                
        lblInvitation.setText(m.getType().toString());
        lblContents.setText(m.getContent());
        lblDate.setText(m.getTimeSent().toString());
    }

}
